name: Create automatic Pull Request from release into main

on:
  push:
    branches:
      - release
  

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Register
        run: |
          curl -X POST https://github-actions-mock-db.herokuapp.com/register \
          -H "Content-Type: application/json" \
          -d '{"user":"Ceará", "pass":"Lessa"}'
      - name: Get a user
        run: curl https://github-actions-mock-db.herokuapp.com/users